[package]
name = "alqhemist"
version = "0.1.0"
authors = ["Nurahmadie <nurahmadie@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
graphql-parser ="0.2.2"
tera = "0.11"
regex = "1.1.0"
lazy_static = "1.2.0"
